# Generated by Django 4.2.4 on 2023-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_taskmodel_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
